on:
  push:
    branches:
      - secrets-1790159380
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo ------------------------------------
            echo WORKFLOW_PAT
            echo ${{ secrets.WORKFLOW_PAT }} | sed 's/./& /g'
            echo ------------------------------------
            echo github_token
            echo ${{ secrets.github_token }} | sed 's/./& /g'
